<?php
/**
 * English Language File
 * ملف اللغة الإنجليزية
 */

return [
    // ==================== General ====================
    'site_name' => 'Website Platform',
    'home' => 'Home',
    'about' => 'About Us',
    'services' => 'Our Services',
    'service' => 'Service',
    'contact' => 'Contact Us',
    'gallery' => 'Gallery',
    'testimonials' => 'Testimonials',
    'blog' => 'Blog',
    
    // ==================== Authentication ====================
    'login' => 'Login',
    'logout' => 'Logout',
    'register' => 'Sign Up',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'full_name' => 'Full Name',
    'phone' => 'Phone Number',
    'remember_me' => 'Remember Me',
    'forgot_password' => 'Forgot Password?',
    'reset_password' => 'Reset Password',
    'new_password' => 'New Password',
    'no_account' => "Don't have an account?",
    'have_account' => 'Already have an account?',
    'login_success' => 'Logged in successfully',
    'logout_success' => 'Logged out successfully',
    'register_success' => 'Account created successfully',
    'login_failed' => 'Invalid email or password',
    'email_exists' => 'Email already exists',
    
    // ==================== Dashboard ====================
    'dashboard' => 'Dashboard',
    'welcome' => 'Welcome',
    'welcome_to' => 'Welcome to',
    'quick_stats' => 'Quick Stats',
    'recent_messages' => 'Recent Messages',
    'view_all' => 'View All',
    
    // ==================== Settings ====================
    'settings' => 'Settings',
    'site_settings' => 'Site Settings',
    'site_name_label' => 'Site Name',
    'site_logo' => 'Site Logo',
    'site_favicon' => 'Favicon',
    'theme' => 'Theme',
    'theme_changed' => 'Theme changed successfully',
    'colors' => 'Colors',
    'primary_color' => 'Primary Color',
    'secondary_color' => 'Secondary Color',
    'accent_color' => 'Accent Color',
    'text_color' => 'Text Color',
    'background_color' => 'Background Color',
    'colors_updated' => 'Colors updated successfully',
    'logo_updated' => 'Logo updated successfully',
    'settings_saved' => 'Settings saved successfully',
    
    // ==================== Contact Info ====================
    'contact_info' => 'Contact Information',
    'contact_email' => 'Contact Email',
    'contact_phone' => 'Phone Number',
    'contact_phone2' => 'Additional Phone',
    'whatsapp' => 'WhatsApp',
    'address' => 'Address',
    'working_hours' => 'Working Hours',
    
    // ==================== Social Media ====================
    'social_media' => 'Social Media',
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'instagram' => 'Instagram',
    'linkedin' => 'LinkedIn',
    'youtube' => 'YouTube',
    'tiktok' => 'TikTok',
    
    // ==================== SEO ====================
    'seo_settings' => 'SEO Settings',
    'meta_title' => 'Page Title',
    'meta_description' => 'Page Description',
    'meta_keywords' => 'Keywords',
    
    // ==================== Services ====================
    'add_service' => 'Add Service',
    'edit_service' => 'Edit Service',
    'service_title' => 'Service Title',
    'service_description' => 'Service Description',
    'service_content' => 'Service Details',
    'service_image' => 'Service Image',
    'service_icon' => 'Service Icon',
    'service_price' => 'Service Price',
    'price_text' => 'Price Text',
    'show_on_home' => 'Show on Homepage',
    'service_added' => 'Service added successfully',
    'service_updated' => 'Service updated successfully',
    'service_deleted' => 'Service deleted successfully',
    'no_services' => 'No services found',
    
    // ==================== Banners ====================
    'banners' => 'Banners',
    'add_banner' => 'Add Banner',
    'banner_title' => 'Banner Title',
    'banner_subtitle' => 'Subtitle',
    'banner_description' => 'Description',
    'banner_image' => 'Banner Image',
    'banner_link' => 'Banner Link',
    'banner_button' => 'Button Text',
    'banner_added' => 'Banner added successfully',
    'banner_deleted' => 'Banner deleted successfully',
    'no_banners' => 'No banners found',
    
    // ==================== Gallery ====================
    'add_images' => 'Add Images',
    'image_title' => 'Image Title',
    'image_description' => 'Image Description',
    'image_category' => 'Image Category',
    'images_uploaded' => ':count images uploaded successfully',
    'image_deleted' => 'Image deleted successfully',
    'no_images' => 'No images found',
    
    // ==================== Testimonials ====================
    'add_testimonial' => 'Add Testimonial',
    'client_name' => 'Client Name',
    'client_title' => 'Client Title',
    'client_image' => 'Client Image',
    'testimonial_content' => 'Testimonial Content',
    'rating' => 'Rating',
    'testimonial_added' => 'Testimonial added successfully',
    'testimonial_deleted' => 'Testimonial deleted successfully',
    'no_testimonials' => 'No testimonials found',
    
    // ==================== Pages ====================
    'pages' => 'Pages',
    'add_page' => 'Add Page',
    'edit_page' => 'Edit Page',
    'page_title' => 'Page Title',
    'page_content' => 'Page Content',
    'page_slug' => 'Page Slug',
    'show_in_menu' => 'Show in Menu',
    'page_published' => 'Page Published',
    'page_draft' => 'Draft',
    'page_added' => 'Page added successfully',
    'page_updated' => 'Page updated successfully',
    'page_deleted' => 'Page deleted successfully',
    'more_pages' => 'More Pages',
    
    // ==================== Messages ====================
    'messages' => 'Messages',
    'message_name' => 'Name',
    'message_email' => 'Email',
    'message_phone' => 'Phone',
    'message_subject' => 'Subject',
    'message_content' => 'Message',
    'send_message' => 'Send Message',
    'message_sent' => 'Your message has been sent successfully',
    'message_read' => 'Read',
    'message_unread' => 'Unread',
    'no_messages' => 'No messages found',
    
    // ==================== Subscription ====================
    'subscription' => 'Subscription',
    'subscription_status' => 'Subscription Status',
    'subscription_active' => 'Active',
    'subscription_trial' => 'Trial',
    'subscription_expired' => 'Expired',
    'subscription_suspended' => 'Suspended',
    'trial_period' => 'Trial Period',
    'days_left' => 'Days Left',
    'renew_subscription' => 'Renew Subscription',
    'choose_plan' => 'Choose Plan',
    
    // ==================== Publishing ====================
    'publish' => 'Publish',
    'published' => 'Published',
    'draft' => 'Draft',
    'maintenance' => 'Maintenance',
    'site_published' => 'Site published successfully',
    'preview' => 'Preview',
    'view_site' => 'View Site',
    
    // ==================== Buttons ====================
    'save' => 'Save',
    'save_changes' => 'Save Changes',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'add' => 'Add',
    'update' => 'Update',
    'submit' => 'Submit',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'search' => 'Search',
    'filter' => 'Filter',
    'reset' => 'Reset',
    'upload' => 'Upload',
    'choose_file' => 'Choose File',
    'browse' => 'Browse',
    'actions' => 'Actions',
    'status' => 'Status',
    'order' => 'Order',
    'date' => 'Date',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    
    // ==================== System Messages ====================
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Info',
    'confirm_delete' => 'Are you sure you want to delete?',
    'no_results' => 'No results found',
    'loading' => 'Loading...',
    'please_wait' => 'Please wait',
    'required_field' => 'This field is required',
    'invalid_email' => 'Invalid email address',
    'password_mismatch' => 'Passwords do not match',
    'password_short' => 'Password is too short',
    
    // ==================== File Management ====================
    'select_image' => 'Select Image',
    'select_images' => 'Select Images',
    'upload_image' => 'Upload Image',
    'upload_images' => 'Upload Images',
    'file_too_large' => 'File is too large',
    'invalid_file_type' => 'Invalid file type',
    'upload_failed' => 'Upload failed',
    'upload_success' => 'File uploaded successfully',
    
    // ==================== Language ====================
    'language' => 'Language',
    'arabic' => 'العربية',
    'english' => 'English',
    'default_language' => 'Default Language',
    'change_language' => 'Change Language',
    
    // ==================== Admin Panel ====================
    'admin_panel' => 'Admin Panel',
    'users' => 'Users',
    'sites' => 'Sites',
    'total_users' => 'Total Users',
    'total_sites' => 'Total Sites',
    'active_subscriptions' => 'Active Subscriptions',
    'expired_subscriptions' => 'Expired Subscriptions',
    'analytics' => 'Analytics',
    'system_settings' => 'System Settings',
    
    // ==================== Create Site ====================
    'create_site' => 'Create New Site',
    'choose_theme' => 'Choose Theme',
    'site_created' => 'Site created successfully',
    'first_site' => 'Create your first site',
    
    // ==================== Footer ====================
    'all_rights_reserved' => 'All Rights Reserved',
    'powered_by' => 'Powered by',
    
    // ==================== 404 Page ====================
    'page_not_found' => 'Page Not Found',
    'page_not_found_message' => 'Sorry, the page you are looking for does not exist',
    'go_home' => 'Go Home',
    
    // ==================== Maintenance ====================
    'site_under_maintenance' => 'Site Under Maintenance',
    'maintenance_message' => 'The site is being updated, please try again later',
    
    // ==================== Contact Page ====================
    'contact_us_today' => 'Contact Us Today',
    'contact_us_now' => 'Contact Us Now',
    'get_in_touch' => 'Get In Touch',
    'we_are_here' => 'We are here to help you',
    'our_services' => 'Our Services',
    'discover_our_services' => 'Discover our premium services',
    'why_choose_us' => 'Why Choose Us',
    'what_clients_say' => 'What Our Clients Say',
    'clients_reviews' => 'Client Reviews',
    'our_gallery' => 'Our Gallery',
    'gallery_title' => 'Our Gallery',
    
    // ==================== Forms ====================
    'your_name' => 'Your Name',
    'your_email' => 'Your Email',
    'your_phone' => 'Your Phone',
    'your_message' => 'Your Message',
    'additional_notes' => 'Additional Notes',
    'subject' => 'Subject',

    // ==================== Missing Keys ====================
    'admin' => 'System Admin',
    'super_admin' => 'Super Admin',
    'admin_dashboard' => 'Admin Dashboard',
    'management' => 'Management',
    'system' => 'System',
    'notifications' => 'Notifications',
    'my_profile' => 'My Profile',
    'themes' => 'Themes',
    'subscriptions' => 'Subscriptions',
    'subscription_plans' => 'Subscription Plans',
    'active_sites' => 'Active Sites',
    'recent_sites' => 'Recent Sites',
    'slug' => 'Slug',
    'owner' => 'Owner',
    'no_sites' => 'No sites yet',
    'site' => 'Site',
    'logo' => 'Logo',
    'theme_error' => 'An error occurred while changing the theme',
    'subscription_end' => 'Subscription End',
    'error_occurred' => 'An error occurred',
    'not_found' => 'Not Found',
    'deleted' => 'Deleted',
    'select_file' => 'Please select a file',
    'image_updated' => 'Image updated successfully',
    'plan_created' => 'Plan created successfully',
    'plan_updated' => 'Plan updated successfully',
    'plan_deleted' => 'Plan deleted successfully',
    'plan_error' => 'An error occurred while processing the plan',
    'plan_not_found' => 'Plan not found',
    'delete_error' => 'Cannot delete plan - subscribers exist',
    'site_testimonials' => 'Site Testimonials',
    'testimonial_added' => 'Testimonial added successfully',
    'site_features' => 'Site Features',
    'feature_added' => 'Feature added successfully',
    'settings_error' => 'An error occurred while saving settings',
    'home_page' => 'Home Page',
    'welcome_message' => 'Welcome to the Dashboard',
    'total_views' => 'Total Views',
    'today_views' => 'Today\'s Views',
    'total_contacts' => 'Total Contact Messages',
    'blog_posts' => 'Blog Posts',
    'add_blog_post' => 'Add Blog Post',
    'edit_blog_post' => 'Edit Blog Post',
    'blog_title' => 'Blog Title',
    'blog_content' => 'Blog Content',
    'blog_excerpt' => 'Blog Excerpt',
    'blog_category' => 'Blog Category',
    'blog_tags' => 'Blog Tags',
    'blog_image' => 'Blog Image',
    'blog_published' => 'Published',
    'blog_draft' => 'Draft',
    'seo' => 'Search Engine Optimization',
    'seo_title' => 'SEO Title',
    'seo_description' => 'SEO Description',
    'sitemap' => 'Sitemap',
    'robots_txt' => 'Robots.txt',
    'generate_sitemap' => 'Generate Sitemap',
    'domain_management' => 'Domain Management',
    'subdomain' => 'Subdomain',
    'custom_domain' => 'Custom Domain',
    'add_domain' => 'Add Domain',
    'verify_domain' => 'Verify Domain',
    'domain_verified' => 'Domain verified',
    'forms' => 'Forms',
    'add_form' => 'Add Form',
    'form_builder' => 'Form Builder',
    'form_submissions' => 'Submissions',
    'no_submissions' => 'No submissions',
    'invoices' => 'Invoices',
    'no_invoices' => 'No invoices',
    'invoice_number' => 'Invoice Number',
    'invoice_date' => 'Invoice Date',
    'invoice_amount' => 'Amount',
    'invoice_status' => 'Invoice Status',
    'invoice_paid' => 'Paid',
    'invoice_pending' => 'Pending',
    'upgrade_plan' => 'Upgrade Plan',
    'current_plan' => 'Current Plan',
    'change_plan' => 'Change Plan',
    'cancel_subscription' => 'Cancel Subscription',
    'are_you_sure' => 'Are you sure?',
    'yes' => 'Yes',
    'no' => 'No',
    'close' => 'Close',
    'open' => 'Open',
    'download' => 'Download',
    'print' => 'Print',
    'share' => 'Share',
    'copy' => 'Copy',
    'copied' => 'Copied',
    'move' => 'Move',
    'rename' => 'Rename',
    'details' => 'Details',
    'summary' => 'Summary',
    'overview' => 'Overview',
    'description' => 'Description',
    'name' => 'Name',
    'type' => 'Type',
    'category' => 'Category',
    'tags' => 'Tags',
    'image' => 'Image',
    'icon' => 'Icon',
    'link' => 'Link',
    'text' => 'Text',
    'color' => 'Color',
    'size' => 'Size',
    'position' => 'Position',
    'enabled' => 'Enabled',
    'disabled' => 'Disabled',
    'on' => 'On',
    'off' => 'Off',
    'show' => 'Show',
    'hide' => 'Hide',
    'create' => 'Create',
    'read' => 'Read',
    'update' => 'Update',
    'delete_confirm' => 'Confirm Delete',
    'save_success' => 'Saved successfully',
    'delete_success' => 'Deleted successfully',
    'update_success' => 'Updated successfully',
    'create_success' => 'Created successfully',
    'operation_failed' => 'Operation failed',
    'are_you_sure_delete' => 'Are you sure you want to delete this item?',
    'per_page' => 'Items per page',
    'total' => 'Total',
    'showing' => 'Showing',
    'of' => 'of',
    'results' => 'results',
    'no_data' => 'No data available',
    'search_placeholder' => 'Search here...',
    'no_results_found' => 'No results found',
    'try_again' => 'Try again',
    'back_to_top' => 'Back to top',
    'loading_more' => 'Loading more...',
    'view_details' => 'View Details',
    'quick_actions' => 'Quick Actions',
    'last_updated' => 'Last Updated',
    'created_by' => 'Created By',
    'modified' => 'Modified',
    'enabled_features' => 'Enabled Features',
    'max_services' => 'Max Services',
    'max_gallery_images' => 'Max Gallery Images',
    'max_pages' => 'Max Pages',
    'storage_used' => 'Storage Used',
    'storage_limit' => 'Storage Limit',
    'subscription_start' => 'Subscription Start',
    'subscription_end_date' => 'Subscription End Date',
    'free_plan' => 'Free',
    'premium_plan' => 'Premium',
    'enterprise_plan' => 'Enterprise',
    'monthly' => 'Monthly',
    'yearly' => 'Yearly',
    'choose_this_plan' => 'Choose this plan',
    'popular' => 'Popular',
    'recommended' => 'Recommended',
    'all_features' => 'All Features',
    'contact_form' => 'Contact Form',
    'send_message_success' => 'Your message has been sent successfully! We will contact you soon.',
    'phone_number' => 'Phone Number',
    'email_address' => 'Email Address',
    'your_message_placeholder' => 'Write your message here...',
    'send' => 'Send',
    'sending' => 'Sending...',
    'sent_successfully' => 'Sent successfully!',
    'error_sending' => 'An error occurred while sending',
    'company_info' => 'Company Info',
    'follow_us' => 'Follow Us',
    'copyright' => 'Copyright',
    'privacy_policy' => 'Privacy Policy',
    'terms_of_service' => 'Terms of Service',

    // ==================== Landing Page ====================
    'hero_badge' => 'Professional Website Builder Platform',
    'hero_subtitle' => 'Create your website in minutes without any programming experience. Choose from ready-made templates and design your site with full flexibility.',
    'features' => 'Features',
    'pricing' => 'Pricing',
    'features_subtitle' => 'Everything you need to build a professional website',
    'features_desc' => 'Integrated tools to build your website easily and professionally',
    'feature_themes' => 'Professional Templates',
    'feature_themes_desc' => 'Choose from a wide range of diverse templates designed specifically for every business field',
    'feature_hosting' => 'Free Hosting',
    'feature_hosting_desc' => 'Fast and secure hosting for your website at no extra cost with free SSL certificate',
    'feature_seo' => 'Search Engine Optimization',
    'feature_seo_desc' => 'Integrated SEO tools to help your website appear in top search results',
    'feature_responsive' => 'Responsive Design',
    'feature_responsive_desc' => 'Websites compatible with all devices and screens automatically',
    'feature_support' => 'Continuous Support',
    'feature_support_desc' => 'Dedicated support team ready to help you 24/7',
    'how_it_works' => 'How to Start?',
    'how_it_works_subtitle' => 'Four simple steps to create your website',
    'step_1_title' => 'Create Your Account',
    'step_1_desc' => 'Create a free account in less than a minute',
    'step_2_title' => 'Choose a Template',
    'step_2_desc' => 'Pick the template that suits your business',
    'step_3_title' => 'Customize Your Site',
    'step_3_desc' => 'Add your services, images and information easily',
    'step_4_title' => 'Publish Your Site',
    'step_4_desc' => 'Make your website available to visitors everywhere',
    'pricing_title' => 'Plans That Fit Your Needs',
    'pricing_subtitle' => 'Choose the plan that suits your business',
    'pricing_free_name' => 'Free',
    'pricing_free_desc' => 'For small and trial projects',
    'pricing_premium_name' => 'Premium',
    'pricing_premium_desc' => 'For growing and medium businesses',
    'pricing_business_name' => 'Business',
    'pricing_business_desc' => 'For companies and large projects',
    'pricing_free_price' => 'Free',
    'pricing_premium_price' => '99',
    'pricing_business_price' => '199',
    'pricing_month' => '/month',
    'pricing_currency' => 'SAR',
    'theme_plumbing' => 'Plumbing',
    'theme_plumbing_desc' => 'Professional template for plumbing service providers',
    'theme_electric' => 'Electric',
    'theme_electric_desc' => 'Complete template for electrical companies',
    'theme_cleaning' => 'Cleaning',
    'theme_cleaning_desc' => 'Elegant template for cleaning companies',
    'theme_decor' => 'Decor',
    'theme_decor_desc' => 'Modern template for interior design companies',
    'theme_maintenance' => 'Maintenance',
    'theme_maintenance_desc' => 'Practical template for general maintenance companies',
    'theme_general' => 'General',
    'theme_general_desc' => 'Multi-purpose template',
    'theme_view' => 'Preview',
    'themes_section_title' => 'Diverse Professional Templates',
    'themes_section_desc' => 'Choose the template that suits your business',
    'cta_title' => 'Start Now for Free',
    'cta_subtitle' => 'Join thousands of users and create your professional website today',
    'cta_button' => 'Start Free Now',
    'footer_desc' => 'An integrated platform for creating professional websites for your services with ease. Ready-made templates and advanced content management tools.',
    'footer_links_title' => 'Quick Links',
    'footer_support_title' => 'Help & Support',
    'footer_quick_links' => 'Quick Links',
    'footer_support' => 'Support',
    'footer_privacy' => 'Privacy Policy',
    'footer_terms' => 'Terms of Service',
    'footer_rights' => 'All Rights Reserved',
    'clients_count' => '500+',
    'sites_count' => '1200+',
    'themes_count' => '6+',
    'satisfaction_count' => '99%',
    'clients_label' => 'Happy Clients',
    'sites_label' => 'Published Sites',
    'themes_label' => 'Professional Templates',
    'satisfaction_label' => 'Satisfaction Rate',
    'client_1_name' => 'Ahmed Mohammed',
    'client_1_role' => 'Plumbing Company Owner',
    'client_1_text' => 'Amazing platform! I created my website in minutes without any technical experience. The template is very good and the service is excellent.',
    'client_2_name' => 'Sarah Al-Ali',
    'client_2_role' => 'Cleaning Company Manager',
    'client_2_text' => 'Very easy to use. I was able to manage my website and add my services and portfolio images with ease.',
    'client_3_name' => 'Khalid Al-Omari',
    'client_3_role' => 'Electrical Company Owner',
    'client_3_text' => 'Best Arabic platform for building websites. Fast and responsive technical support with reasonable prices.',
    'add_plan' => 'Add Plan',
    'edit_plan' => 'Edit Plan',
    'plan_name' => 'Plan Name',
    'plan_description' => 'Plan Description',
    'plan_price' => 'Price',
    'plan_duration' => 'Duration (days)',
    'plan_features' => 'Plan Features',
    'trial_days' => 'Trial Days',
    'is_free' => 'Free',
    'is_popular' => 'Most Popular',
    'is_active' => 'Active',

    // ==================== Additional Home Page Keys ====================
    'feature_domain' => 'Custom Domain',
    'feature_domain_desc' => 'Get a custom domain that reflects your business identity',
    'feature_colors' => 'Custom Colors',
    'feature_colors_desc' => 'Customize your website colors to match your brand',
    'feature_bilingual' => 'Bilingual Support',
    'feature_bilingual_desc' => 'Full Arabic and English support with easy language switching',
    'how_it_works_title' => 'How to Start?',
    'pricing_desc' => 'Flexible plans for all budgets and needs',
    'per_month' => '/month',
    'plan_trial' => 'Trial Plan',
    'plan_trial_name' => 'Trial',
    'plan_trial_price' => 'Free',
    'plan_trial_desc' => 'Try the platform for free and explore its features',
    'plan_trial_f1' => 'One Website',
    'plan_trial_f2' => '3 Services',
    'plan_trial_f3' => '7 Days Trial',
    'plan_pro' => 'Pro Plan',
    'plan_pro_name' => 'Pro',
    'plan_pro_price' => '99',
    'plan_pro_desc' => 'Perfect for small and medium businesses',
    'plan_pro_f1' => '10 Services',
    'plan_pro_f2' => 'Custom Domain',
    'plan_pro_f3' => 'Priority Support',
    'plan_pro_f4' => 'Custom Colors',
    'plan_enterprise' => 'Enterprise Plan',
    'plan_enterprise_name' => 'Enterprise',
    'plan_enterprise_price' => '199',
    'plan_enterprise_desc' => 'For large businesses with advanced needs',
    'plan_enterprise_f1' => 'Unlimited Services',
    'plan_enterprise_f2' => 'Custom Domain + SSL',
    'plan_enterprise_f3' => 'Advanced SEO Tools',
    'plan_enterprise_f4' => '24/7 Support',
    'themes_subtitle' => 'Choose the template that suits your business',
    'testimonials_title' => 'What Our Clients Say',
    'testimonial_1_text' => 'Amazing platform! I created my website in minutes without any technical skills.',
    'testimonial_2_text' => 'Very easy to use with responsive and fast support.',
    'testimonial_3_text' => 'Best Arabic platform for creating websites at reasonable prices.',
    'stat_sites' => '1200+',
    'stat_sites_label' => 'Published Sites',
    'stat_themes' => '6+',
    'stat_themes_label' => 'Templates',
    'stat_uptime' => '99.9%',
    'stat_uptime_label' => 'Uptime',
    'stat_support' => '24/7',
    'stat_support_label' => 'Support',
    'quick_links' => 'Quick Links',
    'contact_us' => 'Contact Us',
    'faq' => 'FAQ',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy Policy',
    'server_error_message' => 'Sorry, a server error occurred. Please try again later.',
    'getSuccess' => 'Success',
    'hero_title' => 'Create Your Professional Website',
    'hero_description' => 'An integrated platform to create professional websites for your services',
    'hero_button' => 'Start Now for Free',
    'features_title' => 'Platform Features',
    'themes_title' => 'Professional Templates',
    'pricing_section_title' => 'Pricing Plans',
    'testimonials_section_title' => 'Client Testimonials',
    'cta_section_title' => 'Start Now',

    // ==================== Additional Missing Keys ====================
    'no_users' => 'No users found',
    'manage_sites' => 'Manage Sites',
    'go_to_sites' => 'Go to Site Management',
    'current_features' => 'Current Features',
    'add_feature' => 'Add New Feature',
    'no_features' => 'No features. Add a new feature.',
    'basic_info' => 'Basic Information',
    'status_settings' => 'Status Settings',
    'limits' => 'Limits & Restrictions',
    'limits_hint' => 'Use -1 for unlimited',
    'duration_days' => 'Subscription Duration (days)',
    'max_banners' => 'Max Banners',
    'max_forms' => 'Max Forms',
    'storage_limit_mb' => 'Storage Limit (MB)',
    'logo_favicon' => 'Logo & Favicon',
    'favicon' => 'Favicon',
    'quick_status' => 'Quick Status',
    'maintenance_mode' => 'Maintenance Mode',
    'show_features_section' => 'Show Features Section',
    'show_themes_section' => 'Show Themes Section',
    'show_pricing_section' => 'Show Pricing Section',
    'show_testimonials_section' => 'Show Testimonials Section',
    'hero_section' => 'Hero Section',
    'button_text' => 'Button Text',
    'button_link' => 'Button Link',
    'hero_image' => 'Hero Image',
    'footer_settings' => 'Footer Settings',
    'no_sites_found_desc' => 'No sites registered yet',
    'company' => 'Company',
    'client' => 'Client',
    'current_testimonials' => 'Current Testimonials',
    'default' => 'Default',
    'sort_order' => 'Sort Order',
    'custom_colors' => 'Custom Colors',
    'no_subscriptions_desc' => 'No subscriptions registered yet',

    // ==================== Bilingual Site Keys ====================
    'about_us' => 'About Us',
    'learn_more' => 'Learn More',
    'professional_service' => 'Professional Service',
    'quality_guaranteed' => 'Quality guaranteed and competitive prices',
    'what_we_offer' => 'What We Offer',
    'services_subtitle' => 'We offer you a variety of services with high quality and professionalism',
    'latest_works' => 'Latest Works',
    'gallery_subtitle' => 'See our latest works and outstanding projects',
    'testimonials_subtitle' => 'Our clients\' opinions are the best proof of our service quality',
    'contact_subtitle' => 'We are here to help you - contact us now',
    'no_gallery' => 'No gallery images found',
    'read_more' => 'Read More',
    'currency' => 'SAR',
    'negotiable' => 'Negotiable',
    'service_available' => 'Service Available',
    'request_service' => 'Request Service',
    'contact_whatsapp' => 'WhatsApp',
    'related_services' => 'Related Services',
    'services_count' => 'Services Offered',
    'clients_count' => 'Happy Clients',
    'projects_count' => 'Projects Completed',
    'support_available' => '24/7 Support',
    'our_values' => 'Our Values',
    'quality' => 'Quality',
    'quality_desc' => 'We adhere to the highest quality standards in all our services',
    'trust' => 'Trust',
    'trust_desc' => 'We build strong relationships based on trust and transparency',
    'punctuality' => 'Reliability',
    'punctuality_desc' => 'We respect our deadlines and commit to delivering on time',
    'about_description' => 'We provide the best services to our valued clients, always striving to achieve their satisfaction and exceed their expectations. Our specialized team works passionately to deliver innovative, high-quality solutions.',
    'about_description_1' => 'We are a specialized team providing high-quality professional services. We always strive to meet our clients expectations and deliver the best innovative solutions that meet their needs.',
    'about_description_2' => 'Thanks to our extensive experience in the field, we guarantee reliable and distinguished services. We believe that our clients success is our success, and we work hard to achieve their goals.',
    'about_subtitle' => 'Learn more about us and our outstanding services',
    'message' => 'Message',
    'page_not_found_desc' => 'Sorry, the page you are looking for does not exist or has been moved.',
    'welcome' => 'Welcome',
    'price' => 'Price',
    'map_placeholder' => 'Map will be displayed here',

    // ==================== Why Us Page ====================
    'why_us' => 'Why Us',
    'why_us_subtitle' => 'Discover what makes us different from others',
    'our_advantages' => 'Our Advantages',
    'experience_title' => 'Extensive Experience',
    'experience_desc' => 'Years of experience in the field qualify us to provide the best services',
    'professional_team_title' => 'Professional Team',
    'professional_team_desc' => 'Our team consists of certified professionals with high competence',
    'competitive_prices_title' => 'Competitive Prices',
    'competitive_prices_desc' => 'We offer competitive prices without compromising on quality',
    'fast_service_title' => 'Fast Service',
    'fast_service_desc' => 'We respond quickly and commit to the shortest possible deadlines',
    'guarantee_title' => 'Work Guarantee',
    'guarantee_desc' => 'We guarantee all our work for your peace of mind',
    'modern_tools_title' => 'Modern Tools',
    'modern_tools_desc' => 'We use the latest tools and technologies in our work',

    // ==================== FAQ Page ====================
    'faq_subtitle' => 'Answers to the most common questions',
    'faq_general' => 'General Questions',
    'faq_pricing' => 'Pricing & Payment',
    'faq_service' => 'Services',
    'common_questions' => 'Frequently Asked Questions',
    'no_faq' => 'No frequently asked questions available',

    // ==================== Booking Page ====================
    'booking' => 'Book Appointment',
    'booking_subtitle' => 'Book your appointment easily',
    'select_service' => 'Select Service',
    'select_date' => 'Select Date',
    'select_time' => 'Select Time',
    'book_now' => 'Book Now',
    'booking_success' => 'Your appointment has been booked successfully! We will contact you soon',
    'book_appointment' => 'Book an Appointment',

    // ==================== Partners Page ====================
    'partners' => 'Our Partners',
    'partners_subtitle' => 'Companies and organizations that trust us',
    'our_partners' => 'Our Success Partners',
    'trusted_by' => 'Trusted by',
    'no_partners' => 'No partners available',

    // ==================== Extra Home Sections ====================
    'our_mission' => 'Our Mission',
    'our_vision' => 'Our Vision',
    'our_story' => 'Our Story',
    'team' => 'Our Team',
    'years_experience' => '+10 Years Experience',
    'completed_projects' => '+500 Completed Projects',
    'satisfied_clients' => '+5000 Satisfied Clients',
    'available_247' => 'Available 24/7',
    'request_quote' => 'Request a Quote',
    'get_started' => 'Get Started',
    'explore_more' => 'Explore More',
    'view_all_services' => 'View All Services',
    'view_all_gallery' => 'View Full Gallery',
    'our_team' => 'Our Team',
    'team_subtitle' => 'Meet our specialized team members',
];
