<?php
/**
 * Theme: Nova - FAQ Page
 */
$lang = Language::current(); $dir = Language::direction(); $isRtl = $dir === 'rtl';
$themePrimary = $tenant->primary_color ?? '#6366f1';
$themeSecondary = $tenant->secondary_color ?? '#4f46e5';
$siteBase = '/site/' . $tenant->slug;
?>
<!DOCTYPE html>
<html lang="<?= $lang ?>" dir="<?= $dir ?>">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? lang('faq') ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap<?= $isRtl ? '.rtl' : '' ?>.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=<?= $isRtl ? 'Cairo:wght@300;400;500;600;700;800;900' : 'Poppins:wght@300;400;500;600;700;800;900' ?>&display=swap" rel="stylesheet">
    <style>
        :root{--primary:<?=$themePrimary?>;--primary-dark:<?=$themeSecondary?>;--gradient:linear-gradient(135deg,var(--primary) 0%,var(--primary-dark) 100%);--radius:12px;--radius-lg:20px;--text:#1a1a2e;--text-secondary:#4a4a6a;--bg-alt:#f8f9fc;--border-light:#f0f1f7;--primary-50:color-mix(in srgb,var(--primary) 6%,white);--font:'<?= $isRtl?'Cairo':'Poppins'?>',system-ui,sans-serif;--transition:all .35s cubic-bezier(.4,0,.2,1)}
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{font-family:var(--font);color:var(--text);background:#fff;line-height:1.7}a{text-decoration:none;color:inherit;transition:var(--transition)}img{max-width:100%;height:auto;display:block}ul{list-style:none}.container{max-width:1200px;margin:0 auto;padding:0 1.5rem}
        .nova-navbar{background:rgba(255,255,255,.78);backdrop-filter:blur(24px);position:fixed;width:100%;top:0;z-index:1050;border-bottom:1px solid var(--border-light)}.nova-navbar .container{display:flex;align-items:center;justify-content:space-between;height:76px}.nav-brand{display:flex;align-items:center;gap:.65rem;font-weight:800;font-size:1.2rem;color:var(--primary)}.nav-brand img{height:44px;border-radius:8px}.nav-brand .brand-icon{width:42px;height:42px;background:var(--gradient);border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:1.15rem}.nav-links{display:flex;align-items:center;gap:.1rem}.nav-links>li>a{padding:.5rem .85rem;border-radius:8px;font-weight:500;font-size:.9rem;color:var(--text-secondary)}.nav-links>li>a:hover{color:var(--primary);background:var(--primary-50)}.lang-switch{display:inline-flex;align-items:center;gap:.35rem;padding:.45rem .85rem!important;border:1.5px solid var(--border-light)!important;border-radius:8px!important;font-size:.8rem!important;font-weight:600!important;color:var(--text-secondary)!important}.mobile-btn{display:none;background:none;border:none;font-size:1.35rem;cursor:pointer;color:var(--text);width:42px;height:42px}@media(max-width:992px){.mobile-btn{display:flex;align-items:center;justify-content:center}.nav-links{display:none;position:absolute;top:100%;left:0;right:0;background:#fff;flex-direction:column;padding:.75rem;box-shadow:var(--shadow-lg)}.nav-links.open{display:flex}}
        .page-hero{background:var(--gradient);padding:8rem 1.5rem 4rem;text-align:center}.page-hero h1{color:#fff;font-size:clamp(2rem,4vw,3rem);font-weight:800;margin-bottom:.75rem}.breadcrumb{display:flex;justify-content:center;gap:.5rem;margin-top:1.5rem}.breadcrumb a{color:rgba(255,255,255,.7);font-size:.88rem}.breadcrumb span{color:rgba(255,255,255,.5);font-size:.88rem}.breadcrumb .current{color:#fff;font-weight:600;font-size:.88rem}
        .faq-section{padding:5rem 1.5rem}.faq-grid{max-width:800px;margin:0 auto;display:flex;flex-direction:column;gap:.75rem}.faq-item{background:#fff;border-radius:var(--radius);border:1px solid var(--border-light);overflow:hidden;transition:var(--transition)}.faq-item:hover{border-color:var(--border)}.faq-item.active{border-color:var(--primary);box-shadow:0 2px 16px color-mix(in srgb,var(--primary) 10%,transparent)}.faq-question{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.15rem 1.5rem;cursor:pointer;font-weight:600;font-size:.95rem;color:var(--text);user-select:none}.faq-question:hover{color:var(--primary)}.faq-item.active .faq-question{color:var(--primary)}.faq-toggle{width:32px;height:32px;min-width:32px;border-radius:50%;background:var(--primary-50);display:flex;align-items:center;justify-content:center;color:var(--primary);font-size:.85rem;transition:transform .35s ease,background .3s ease}.faq-item.active .faq-toggle{transform:rotate(180deg);background:var(--primary);color:#fff}.faq-answer{max-height:0;overflow:hidden;transition:max-height .4s cubic-bezier(.4,0,.2,1)}.faq-item.active .faq-answer{max-height:300px}.faq-answer-inner{padding:0 1.5rem 1.25rem;color:var(--text-secondary);font-size:.9rem;line-height:1.8}
        .nova-footer{background:#0f172a;color:rgba(255,255,255,.7);padding:3rem 1.5rem 1.5rem}.footer-bottom{border-top:1px solid rgba(255,255,255,.08);padding-top:1.5rem;text-align:center;font-size:.82rem}.footer-grid{display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr;gap:2.5rem;margin-bottom:3rem}@media(max-width:768px){.footer-grid{grid-template-columns:1fr;text-align:center}}.footer-brand{display:flex;align-items:center;gap:.65rem;margin-bottom:1rem}.footer-brand img{height:40px}.footer-brand .brand-icon{width:38px;height:38px;background:var(--gradient);border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:1rem}.footer-brand span{font-weight:700;color:#fff;font-size:1.1rem}.footer-col h4{color:#fff;font-weight:700;font-size:1rem;margin-bottom:1.25rem}.footer-col ul li{margin-bottom:.65rem}.footer-col ul li a{font-size:.88rem;color:rgba(255,255,255,.6)}.footer-col ul li a:hover{color:#fff}.whatsapp-float{position:fixed;bottom:24px;<?=$isRtl?'left':'right'?>:24px;z-index:1000;width:56px;height:56px;background:#25d366;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#fff;font-size:1.6rem;box-shadow:0 4px 24px rgba(37,211,102,.4)}
    @media (max-width: 480px) { .footer-grid { gap: 1.5rem; } }
    </style>
</head>
<body>
<nav class="nova-navbar"><div class="container">
    <a href="<?=url($siteBase)?>" class="nav-brand"><?php if(!empty($tenant->logo)):?><img src="<?=upload($tenant->logo)?>" alt=""><?php else:?><div class="brand-icon"><i class="fas fa-gem"></i></div><?php endif;?><span><?=htmlspecialchars($tenant->site_name)?></span></a>
    <ul class="nav-links" id="navLinks"><?php if(!empty($menu)):foreach($menu as$item):?><?php $navHref=$siteBase;$s=strtolower($item->slug??'');if($item->is_home==1)$navHref=$siteBase;elseif(strpos($s,'about')!==false)$navHref=$siteBase.'/about';elseif(strpos($s,'service')!==false)$navHref=$siteBase.'/services';elseif(strpos($s,'gallery')!==false)$navHref=$siteBase.'/gallery';elseif(strpos($s,'contact')!==false)$navHref=$siteBase.'/contact';elseif(strpos($s,'faq')!==false)$navHref=$siteBase.'/faq';elseif(strpos($s,'partner')!==false)$navHref=$siteBase.'/partners';elseif(strpos($s,'book')!==false)$navHref=$siteBase.'/booking';elseif(strpos($s,'blog')!==false)$navHref=$siteBase.'/blog';else $navHref=$siteBase.'/'.$item->slug;?><li><a href="<?=url($navHref)?>"><?=htmlspecialchars(localized($item, 'title') ?: $item->title ?? '')?></a></li><?php endforeach;endif;?></ul>
    <div style="display:flex;align-items:center;gap:.5rem;"><a href="<?=url($siteBase.'?lang='.Language::opposite())?>" class="lang-switch"><i class="fas fa-globe"></i> <?=Language::opposite()==='en'?'EN':'عربي'?></a><button class="mobile-btn" id="mobileBtn"><i class="fas fa-bars"></i></button></div>
</div></nav>
<div class="page-hero"><h1><?=lang('faq')?></h1><div class="breadcrumb"><a href="<?=url($siteBase)?>"><?=lang('home')?></a><span>/</span><span class="current"><?=lang('faq')?></span></div></div>
<div class="faq-section"><div class="container">
    <?php if(!empty($faqItems)):?>
    <div class="faq-grid"><?php foreach($faqItems as$faq):?>
        <div class="faq-item"><div class="faq-question" onclick="this.parentElement.classList.toggle('active')"><span><?=htmlspecialchars(localized($faq, 'question') ?: $faq->question ?? '')?></span><div class="faq-toggle"><i class="fas fa-chevron-down"></i></div></div><div class="faq-answer"><div class="faq-answer-inner"><?=htmlspecialchars(localized($faq, 'answer') ?: $faq->answer ?? '')?></div></div></div>
    <?php endforeach;?></div>
    <?php else:?><div style="text-align:center;padding:4rem 0;color:var(--text-secondary);"><i class="fas fa-question-circle" style="font-size:3rem;margin-bottom:1rem;color:var(--primary-50);"></i><p><?=lang('no_faq')?></p></div><?php endif;?>
</div></div>
<footer class="nova-footer"><div class="container"><div class="footer-grid">
    <div><div class="footer-brand"><?php if(!empty($tenant->logo)):?><img src="<?=upload($tenant->logo)?>" alt=""><?php else:?><div class="brand-icon"><i class="fas fa-gem"></i></div><?php endif;?><span><?=htmlspecialchars($tenant->site_name)?></span></div></div>
    <div class="footer-col"><h4><?=lang('quick_links')?></h4><ul><li><a href="<?=url($siteBase)?>"><?=lang('home')?></a></li><li><a href="<?=url($siteBase.'/about')?>"><?=lang('about_us')?></a></li><li><a href="<?=url($siteBase.'/services')?>"><?=lang('our_services')?></a></li></ul></div>
    <div class="footer-col"><h4><?=lang('more_pages')?></h4><ul><li><a href="<?=url($siteBase.'/gallery')?>"><?=lang('gallery')?></a></li><li><a href="<?=url($siteBase.'/contact')?>"><?=lang('contact_us')?></a></li></ul></div>
    <div class="footer-col"><h4><?=lang('contact_info')?></h4><ul><li><a href="tel:<?=htmlspecialchars($tenant->contact_phone??'')?>" dir="ltr"><?=htmlspecialchars($tenant->contact_phone??'')?></a></li></ul></div>
</div><div class="footer-bottom"><p>&copy; <?=date('Y')?> <?=htmlspecialchars($tenant->site_name)?>. <?=lang('all_rights_reserved')?></p></div></div></footer>
<?php if(!empty($tenant->contact_whatsapp)):?><a href="https://wa.me/<?=preg_replace('/[^0-9]/','',$tenant->contact_whatsapp)?>" class="whatsapp-float" target="_blank"><i class="fab fa-whatsapp"></i></a><?php endif;?>
<script>document.getElementById('mobileBtn').addEventListener('click',function(){document.getElementById('navLinks').classList.toggle('open');this.querySelector('i').classList.toggle('fa-bars');this.querySelector('i').classList.toggle('fa-times');});</script>
</body>
</html>
